# Generated by Django 5.2.5 on 2025-09-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='games_won',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='hours_played',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='kills',
        ),
    ]
