# Generated by Django 5.2.7 on 2025-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
