# Generated by Django 5.2.5 on 2025-10-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
