# Generated by Django 5.2.5 on 2025-12-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_message_options'),
        ('social', '0003_alter_message_options_message_display_name'),
    ]

    operations = [
    ]
