GAME_FIELDS = {
    "Valorant": {
        "games_played": "int",
        "games_won": "int",
        "time_played": "int",
        "kills": "int",
        "deaths": "int",
        "assists": "int",
        "current_rank": "char",
    },
    "Overwatch": {
        "games_played": "int",
        "games_won": "int",
        "time_played": "int",
        "kills": "int",
        "deaths": "int",
        "assists": "int",
        "current_rank": "char",
    },
    "League of Legends": {
        "games_played": "int",
        "games_won": "int",
        "time_played": "int",
        "kills": "int",
        "deaths": "int",
        "assists": "int",
        "current_rank": "char",
    },
    "Super Smash Bros Ultimate": {
        "games_played_total": "int",
        "games_won": "int",
        "most_played_character": "char",
        "games_as_most_played": "int",
        "time_played": "int",
        "total_stocks_taken": "int",
    },
    "Rocket League": {
        "games_played": "int",
        "games_won": "int",
        "time_played": "int",
        "game_mode": "char",
        "rank": "char",
    },
}